name: hprose
version: 3.0.0-beta.01
author: Ma Bingyao <mabingyao@gmail.com>
description: Hprose for Dart
homepage: https://github.com/hprose/hprose-dart
environment:
  sdk: '>=2.0.0 <3.0.0'
dev_dependencies:
  test: 'any'
