name: hprose
version: 0.5.0-dev+2.25.2016
author: Ma Bingyao <mabingyao@gmail.com>
description: Hprose for Dart
homepage: https://github.com/hprose/hprose-dart
environment:
  sdk: '>=1.13.0'
dev_dependencies:
  test: 'any'
